spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.243.49:3306/ying?useUnicode=true&characterEncoding=UTF-8
    username: mi
    password: das1aSD2SAf213
  jpa:
    properties: 
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
